### ISSUE TITLE
Allow digits/uppercase at the end of class names

### ISSUE THREAD

**Issue by SolalPirelli** [simhayoz/eval-code-quality#17]
Java has classes like [LayoutManager2](https://docs.oracle.com/en/java/javase/13/docs/api/java.desktop/java/awt/LayoutManager2.html) and [Graphics2D](https://docs.oracle.com/en/java/javase/13/docs/api/java.desktop/java/awt/Graphics2D.html), so the following code should not cause errors:

```java
class Class { }
class Class2 { }
class Class2D { }
```

**Comment by simhayoz** [comment]
Done in #23
