### ISSUE TITLE
Names like `mId` incorrectly detected as all-uppercase

### ISSUE THREAD

**Issue by SolalPirelli** [simhayoz/eval-code-quality#18]
e.g.

```java
class Class {
  int mId;
  int mName;
}
```

I get the logic; remove the first and last letters, and the rest is all-uppercase. But this feels wrong as a human reader. Humans are annoying like that... 🙃 

Here are two ideas I have, feel free to use/not use any of them:
- since suffix-based naming conventions are rare, it may be enough to hardcode known ones like suffixing an underscore; or
- add a notion of "unknown", i.e., in the case of `mId` there is not enough information to tell whether it's really all-uppercase since "all" is 1.

**Comment by simhayoz** [comment]
Good point, I will only remove ~first and~ last character if it is an underscore or dollar and will match the property of the variable for the rest of the word (or the complete word if it does not ~start or~ end with an underscore or dollar)

**Comment by simhayoz** [comment]
Done in #23
